/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Calculadora;

public class FormCalculadora extends javax.swing.JFrame {
    String numberChain = "";
    String operationOnScreen = "";
    Calculadora calculadora;
    FormBitacora bitacora;
    boolean blockNumpad = false;
    boolean stopOperation = false;
    
    public FormCalculadora(Calculadora calculadora, FormBitacora bitacora) {
        this.calculadora = calculadora;
        this.bitacora = bitacora;
        initComponents();
        getContentPane().setBackground(new java.awt.Color(153, 204, 255));
    }
    
    public void resetNumberChain(){
        this.numberChain = "";
    }
    
    public double evaluateNumberChain(){
        try{
            return Double.parseDouble(numberChain);
        }
        catch (Exception e){
            syntaxError();
            this.stopOperation = true;
            return 0;
        }
    }
    
    public void blockNumpad(){
        this.blockNumpad = true;
    }
    
    public void unblockNumpad(){
        this.blockNumpad = false;
    }
    
    public void resetOperationOnScreen(){
        this.operationOnScreen = "";
    }
    
    public void addOperationOnScreen(String digit){
        this.operationOnScreen += digit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrinter = new javax.swing.JTextArea();
        btn0 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnPromedio = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btnBinario = new javax.swing.JButton();
        btnPrimo = new javax.swing.JButton();
        btnData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtPrinter.setEditable(false);
        txtPrinter.setColumns(20);
        txtPrinter.setFont(new java.awt.Font("Dialog", 0, 42)); // NOI18N
        txtPrinter.setRows(5);
        jScrollPane1.setViewportView(txtPrinter);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnDecimal.setText(".");
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });

        btnMultiplicacion.setText("x");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnGuardar.setText("M+");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnPromedio.setText("Avg");
        btnPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioActionPerformed(evt);
            }
        });

        btnResultado.setText("=");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        btnBinario.setText("Binario");
        btnBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinarioActionPerformed(evt);
            }
        });

        btnPrimo.setText("Primo");
        btnPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimoActionPerformed(evt);
            }
        });

        btnData.setText("Data");
        btnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinarioActionPerformed
        if (!"".equals(this.numberChain)){
            if (calculadora.getOperandoAcumulado() == 0){
                if (calculadora.getOperador() != 0)
                    generarResultado();
                else{
                    double operandoAcumulado = evaluateNumberChain();
                    calculadora.setOperandoAcumulado(operandoAcumulado);                    
                }                
            }
            else generarResultado();
        }
        if (this.stopOperation == true){
            this.stopOperation = false;
            return;
        }
        if (calculadora.getAcumuladoNull() == false){
            double resultado = calculadora.operacionBinario(); 
            long wholeResultado = (long) resultado;
            if (resultado >= Long.MAX_VALUE){
                syntaxError();
                return;
            }
            calculadora.write("Binario " + this.operationOnScreen + " = " + Long.toString(wholeResultado) + "\n");
            calculadora.setOperandoAcumulado(resultado);
            calculadora.setOperador(0);
            resetNumberChain();
            blockNumpad();
            resetOperationOnScreen();
            addOperationOnScreen(Long.toString(wholeResultado));
            this.txtPrinter.setText(this.operationOnScreen);    
        }
    }//GEN-LAST:event_btnBinarioActionPerformed

    private void btnPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimoActionPerformed
        if (!"".equals(this.numberChain)){
            if (calculadora.getOperandoAcumulado() == 0){
                if (calculadora.getOperador() != 0)
                    generarResultado();
                else{
                    double operandoAcumulado = evaluateNumberChain();
                    calculadora.setOperandoAcumulado(operandoAcumulado);                    
                }                
            }
            else generarResultado();
        }
        if (this.stopOperation == true){
            this.stopOperation = false;
            return;
        }
        if (calculadora.getAcumuladoNull() == false){
            boolean resultado = calculadora.esPrimo();
            calculadora.write("Primo " + this.operationOnScreen + " " + Boolean.toString(resultado) + "\n");
            calculadora.setOperandoAcumulado(0);
            calculadora.setOperador(0);
            calculadora.resetAcumuladoNull();
            resetNumberChain();
            resetOperationOnScreen();
            unblockNumpad();
            this.txtPrinter.setText(Boolean.toString(resultado));
        }
    }//GEN-LAST:event_btnPrimoActionPerformed

    private void btnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActionPerformed
        if (this.bitacora.isVisible())
            this.bitacora.setVisible(false);
        else
            this.bitacora.setVisible(true);
    }//GEN-LAST:event_btnDataActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "0";
            addOperationOnScreen("0");
            this.txtPrinter.setText(this.operationOnScreen);
        } 
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "1";
            addOperationOnScreen("1");
            this.txtPrinter.setText(this.operationOnScreen);            
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "2";
            addOperationOnScreen("2");
            this.txtPrinter.setText(this.operationOnScreen);            
        }            
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "3";
            addOperationOnScreen("3");
            this.txtPrinter.setText(this.operationOnScreen);    
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "4";
            addOperationOnScreen("4");
            this.txtPrinter.setText(this.operationOnScreen);            
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "5";
            addOperationOnScreen("5");
            this.txtPrinter.setText(this.operationOnScreen);            
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "6";
            addOperationOnScreen("6");
            this.txtPrinter.setText(this.operationOnScreen);            
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "7";
            addOperationOnScreen("7");
            this.txtPrinter.setText(this.operationOnScreen);            
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "8";
            addOperationOnScreen("8");
            this.txtPrinter.setText(this.operationOnScreen);            
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (!this.blockNumpad) {
            this.numberChain += "9";
            addOperationOnScreen("9");
            this.txtPrinter.setText(this.operationOnScreen);            
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        if (!this.blockNumpad) {                                                      
            this.numberChain += ".";
            addOperationOnScreen(".");
            this.txtPrinter.setText(this.operationOnScreen);            
        }
    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
            generarResultado();
            this.stopOperation = false;
    }//GEN-LAST:event_btnResultadoActionPerformed

    public void generarResultado(){
        if (!"".equals(this.numberChain)){        
            double operando = evaluateNumberChain();
            if (this.stopOperation == true){
                return;
            }
            if (operando == 0 && calculadora.getOperador() == 4){                           
                syntaxError();
                this.stopOperation = true;
                return;
            }
            if (calculadora.getOperador() == 0)
                calculadora.setOperador(1);
            double resultado = calculadora.operacionBasica(operando);                       
            calculadora.setOperandoAcumulado(resultado);
            calculadora.setOperador(0);
            calculadora.write(this.operationOnScreen);
            resetNumberChain();
            blockNumpad();
            resetOperationOnScreen();
            long wholeResultado = (long) resultado;
            if (resultado%1 == 0)
                addOperationOnScreen(Long.toString(wholeResultado));
            else
                addOperationOnScreen(Double.toString(resultado));
            calculadora.write(" = " + this.operationOnScreen + "\n");
            this.txtPrinter.setText(this.operationOnScreen);
        }
    }
    
    public void syntaxError(){
        calculadora.setOperandoAcumulado(0);
        calculadora.setOperador(0);
        calculadora.resetAcumuladoNull();
        resetNumberChain();
        resetOperationOnScreen();
        unblockNumpad();
        this.txtPrinter.setText("SYNTAX ERROR");
    }
    
    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        if (!"".equals(this.numberChain)){
            if (calculadora.getOperandoAcumulado() == 0){
                if (calculadora.getOperador() != 0)
                    generarResultado();
                else{
                    double operandoAcumulado = evaluateNumberChain();
                    calculadora.setOperandoAcumulado(operandoAcumulado);
                }
            }
            else generarResultado();
        }
        if (this.stopOperation == true){
            this.stopOperation = false;
            return;
        }
        if (calculadora.getOperador() == 0 || calculadora.getOperador() == 1)
            calculadora.setOperador(1);
        resetNumberChain();
        unblockNumpad();
        addOperationOnScreen(" + ");
        this.txtPrinter.setText(this.operationOnScreen);
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        resetNumberChain();
        calculadora.setOperandoAcumulado(0);
        calculadora.setOperador(0);
        calculadora.resetAcumuladoNull();
        unblockNumpad();
        resetOperationOnScreen();
        this.txtPrinter.setText(this.operationOnScreen);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        if (!"".equals(this.numberChain)){                     
            if (calculadora.getOperandoAcumulado() == 0){
                if (calculadora.getOperador() != 0)
                    generarResultado();
                else{
                    double operandoAcumulado = evaluateNumberChain();
                    calculadora.setOperandoAcumulado(operandoAcumulado);                    
                }
            }
            else generarResultado();
        }
        if (this.stopOperation == true){
            this.stopOperation = false;
            return;
        }
        if (calculadora.getOperador() == 2)
            calculadora.setOperador(1);
        else if (calculadora.getOperador() == 3){
            double operandoAcumulado2 = calculadora.getOperandoAcumulado();
            calculadora.setOperandoAcumulado(operandoAcumulado2 * -1);
            calculadora.setOperador(3);
            }
        else if (calculadora.getOperador() == 4){
            double operandoAcumulado2 = calculadora.getOperandoAcumulado();
            calculadora.setOperandoAcumulado(operandoAcumulado2 * -1);
            calculadora.setOperador(4);
        }
        else
            calculadora.setOperador(2);
        resetNumberChain();
        unblockNumpad();
        addOperationOnScreen(" - ");
        this.txtPrinter.setText(this.operationOnScreen);
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        if (!"".equals(this.numberChain)){                                                                                       
            if (calculadora.getOperandoAcumulado() == 0){
                if (calculadora.getOperador() != 0)
                    generarResultado();
                else{
                    double operandoAcumulado = evaluateNumberChain();
                    calculadora.setOperandoAcumulado(operandoAcumulado);                    
                }                
            }
            else generarResultado();
        }
        if (this.stopOperation == true){
            this.stopOperation = false;
            return;
        }
        if (calculadora.getOperador() != 0 || calculadora.getAcumuladoNull() == true){
            syntaxError();
            return;
        }
        else
            calculadora.setOperador(3);
        resetNumberChain();
        unblockNumpad();
        addOperationOnScreen(" * ");
        this.txtPrinter.setText(this.operationOnScreen);
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        if (!"".equals(this.numberChain)){                     
            if (calculadora.getOperandoAcumulado() == 0){
                if (calculadora.getOperador() != 0)
                    generarResultado();
                else{
                    double operandoAcumulado = evaluateNumberChain();
                    calculadora.setOperandoAcumulado(operandoAcumulado);                    
                }                
            }
            else generarResultado();
        }
        if (this.stopOperation == true){
            this.stopOperation = false;
            return;
        }
        if (calculadora.getOperador() != 0 || calculadora.getAcumuladoNull() == true){
            syntaxError();
            return;  
        }
        else
            calculadora.setOperador(4);
        resetNumberChain();
        unblockNumpad();
        addOperationOnScreen(" / ");
        this.txtPrinter.setText(this.operationOnScreen);
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!"".equals(this.numberChain)){
            if (calculadora.getOperandoAcumulado() == 0){
                if (calculadora.getOperador() != 0)
                    generarResultado();
                else{
                    double operandoAcumulado = evaluateNumberChain();
                    calculadora.setOperandoAcumulado(operandoAcumulado);                    
                }                
            }
            else generarResultado();
        }
        if (this.stopOperation == true){
            this.stopOperation = false;
            return;
        }
        if (calculadora.getAcumuladoNull() == false){
            double result = calculadora.getOperandoAcumulado();
            String memory = calculadora.getMemory();
            calculadora.write("M+ " + Double.toString(result) + " > " + memory + "\n");
            calculadora.saveInMemory(result);                                 
            System.out.println("Added " + result + " to memory");
            resetNumberChain();
            blockNumpad();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioActionPerformed
        double resultado = calculadora.operacionPromedio();
        String memory = calculadora.getMemory();
        calculadora.write("Avg " + memory + " = " + Double.toString(resultado) + "\n");
        calculadora.setOperandoAcumulado(resultado);
        calculadora.setOperador(0);
        resetNumberChain();
        blockNumpad();
        resetOperationOnScreen();
        long wholeResultado = (long) resultado;
        if (resultado%1 == 0)
            addOperationOnScreen(Long.toString(wholeResultado));
        else
            addOperationOnScreen(Double.toString(resultado));
        this.txtPrinter.setText(this.operationOnScreen);        
    }//GEN-LAST:event_btnPromedioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBinario;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnData;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnPrimo;
    private javax.swing.JButton btnPromedio;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSuma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPrinter;
    // End of variables declaration//GEN-END:variables
}
